-- Online contract matching the offline mock backend.
-- Non-destructive: adds missing columns, indexes, policies, and RPCs while preserving existing data.

alter table public.projects add column if not exists status text not null default 'running';
update public.projects set status = 'running' where status is null;
alter table public.projects drop constraint if exists projects_status_check;
alter table public.projects add constraint projects_status_check check (status in ('draft','ready','running','stopped','not_wanted','completed'));

alter table public.buildings add column if not exists weight_percent numeric not null default 0;
alter table public.buildings drop constraint if exists buildings_weight_percent_check;
alter table public.buildings add constraint buildings_weight_percent_check check (weight_percent >= 0 and weight_percent <= 100);

alter table public.project_tasks add column if not exists category text, add column if not exists assigned_employee_id uuid references public.employees(id) on delete set null, add column if not exists assigned_team text, add column if not exists priority text not null default 'normal', add column if not exists status text not null default 'not_started', add column if not exists planned_start date, add column if not exists planned_finish date, add column if not exists actual_start date, add column if not exists actual_finish date;
alter table public.project_tasks drop constraint if exists project_tasks_priority_check;
alter table public.project_tasks add constraint project_tasks_priority_check check (priority in ('low','normal','high','urgent'));
alter table public.project_tasks drop constraint if exists project_tasks_status_check;
alter table public.project_tasks add constraint project_tasks_status_check check (status in ('not_started','in_progress','blocked','under_review','revision_required','completed','cancelled','on_hold'));

alter table public.report_batches add column if not exists employee_id uuid references public.employees(id) on delete set null, add column if not exists submitted_by uuid references auth.users(id) on delete set null, add column if not exists work_date date;
update public.report_batches rb set employee_id = e.id from public.employees e where rb.employee_id is null and rb.employee_name = e.name;
update public.report_batches set work_date = created_at::date where work_date is null;
update public.report_batches set submitted_by = created_by where submitted_by is null;

alter table public.report_lines add column if not exists project_task_id uuid references public.project_tasks(id) on delete set null, add column if not exists activity text, add column if not exists hours_worked numeric, add column if not exists blocker text;

create table if not exists public.task_activities (id uuid primary key default gen_random_uuid(), project_task_id uuid references public.project_tasks(id) on delete set null, employee_id uuid references public.employees(id) on delete set null, employee_name text, activity_date date not null default current_date, description text not null, previous_percent numeric not null default 0 check (previous_percent >= 0 and previous_percent <= 100), new_percent numeric not null check (new_percent >= 0 and new_percent <= 100), hours_worked numeric check (hours_worked is null or hours_worked >= 0), blocker text, note text, kind text not null default 'report' check (kind in ('report','override')), report_line_id uuid references public.report_lines(id) on delete set null, recorded_by uuid references auth.users(id) on delete set null, reason text, created_at timestamptz not null default now());
alter table public.task_activities add column if not exists employee_name text, add column if not exists kind text not null default 'report', add column if not exists report_line_id uuid references public.report_lines(id) on delete set null, add column if not exists recorded_by uuid references auth.users(id) on delete set null, add column if not exists reason text;
alter table public.task_activities drop constraint if exists task_activities_kind_check;
alter table public.task_activities add constraint task_activities_kind_check check (kind in ('report','override'));

alter table public.attendance add column if not exists attendance_date date, add column if not exists entrance_time text, add column if not exists status text not null default 'present';
update public.attendance set attendance_date = date where attendance_date is null;
update public.attendance set entrance_time = arrival_time where entrance_time is null;
update public.attendance set status = case when is_day_off then 'day_off' else 'present' end where status is null;
alter table public.attendance drop constraint if exists attendance_status_check;
alter table public.attendance add constraint attendance_status_check check (status in ('present','late','day_off','hours_off','absent'));

create index if not exists project_tasks_assigned_employee_idx on public.project_tasks(assigned_employee_id);
create index if not exists report_batches_employee_idx on public.report_batches(employee_id);
create index if not exists report_batches_work_date_idx on public.report_batches(work_date);
create index if not exists task_activities_task_date_idx on public.task_activities(project_task_id, activity_date desc, created_at desc);

create or replace function public.submit_report(p_groups jsonb, p_work_date date default current_date, p_on_behalf_of uuid default null) returns uuid[] language plpgsql security definer set search_path = public as $$
declare
  v_caller public.profiles%rowtype; v_employee public.employees%rowtype; v_batch_id uuid; v_batch_ids uuid[] := '{}'; v_group jsonb; v_line jsonb; v_project_id uuid; v_building_id uuid; v_report_line_id uuid; v_current numeric; v_flag text; v_dept text; v_task text; v_pct numeric; v_note text; v_activity text; v_hours numeric; v_blocker text; v_project public.projects%rowtype; v_building public.buildings%rowtype; v_task_row public.project_tasks%rowtype;
begin
  select * into v_caller from public.profiles where id = auth.uid() and active = true; if not found then raise exception 'Not authenticated'; end if;
  if p_work_date is null or p_work_date <> current_date then raise exception 'Reports can only be submitted for today.'; end if;
  if p_groups is null or jsonb_typeof(p_groups) <> 'array' or jsonb_array_length(p_groups) = 0 then raise exception 'Report must include at least one project/building group'; end if;
  if p_on_behalf_of is not null then if v_caller.role <> 'manager' then raise exception 'Only a manager can submit a report on behalf of another employee.'; end if; select * into v_employee from public.employees where id = p_on_behalf_of; else select * into v_employee from public.employees where id = v_caller.employee_id; end if; if not found then raise exception 'Your account is not linked to an employee record.'; end if;
  for v_group in select value from jsonb_array_elements(p_groups) loop
    v_project_id := nullif(v_group->>'project_id','')::uuid; v_building_id := nullif(v_group->>'building_id','')::uuid; select * into v_project from public.projects where id = v_project_id; if not found then raise exception 'Project not found.'; end if; if v_project.status in ('completed','stopped','not_wanted') then raise exception 'Project is closed and no longer accepts progress reports.'; end if; select * into v_building from public.buildings where id = v_building_id and project_id = v_project_id; if not found then raise exception 'The selected building does not belong to the selected project.'; end if; if v_group->'lines' is null or jsonb_typeof(v_group->'lines') <> 'array' or jsonb_array_length(v_group->'lines') = 0 then raise exception 'Each group requires at least one task'; end if;
    insert into public.report_batches(employee_id, employee_name, submitted_by, project_id, building_id, work_date, created_by) values (v_employee.id, v_employee.name, auth.uid(), v_project_id, v_building_id, current_date, auth.uid()) returning id into v_batch_id; v_batch_ids := v_batch_ids || v_batch_id;
    for v_line in select value from jsonb_array_elements(v_group->'lines') loop
      v_dept := nullif(trim(v_line->>'department'),''); v_task := nullif(trim(v_line->>'task'),''); v_pct := nullif(v_line->>'percentage','')::numeric; v_activity := nullif(trim(v_line->>'activity'),''); v_note := nullif(trim(v_line->>'note'),''); v_blocker := nullif(trim(v_line->>'blocker'),''); v_hours := nullif(v_line->>'hours_worked','')::numeric; if v_dept is null or v_task is null then raise exception 'Each task line needs a department and a task.'; end if; if v_pct is null or v_pct < 0 or v_pct > 100 then raise exception 'Percentage must be a number between 0 and 100.'; end if; if v_activity is null then raise exception 'Each task line needs a description of the work done.'; end if; if v_hours is not null and (v_hours < 0 or v_hours > 24) then raise exception 'Hours worked must be between 0 and 24.'; end if;
      select * into v_task_row from public.project_tasks where project_id = v_project_id and building_id = v_building_id and department = v_dept and (task = v_task or task = '') order by case when task = v_task then 0 else 1 end, id limit 1 for update; if not found then insert into public.project_tasks(project_id, building_id, department, task, weight_percent, completion_percent, priority, status) values (v_project_id, v_building_id, v_dept, v_task, 0, 0, 'normal', 'not_started') returning * into v_task_row; end if; if v_task_row.assigned_employee_id is not null and v_task_row.assigned_employee_id <> v_employee.id then raise exception 'This task is assigned to another employee.'; end if; if v_task_row.status = 'cancelled' then raise exception 'This task is cancelled and cannot receive progress.'; end if; v_current := coalesce(v_task_row.completion_percent, 0); if v_pct <= v_current and v_note is null then raise exception 'A reason is required when progress is unchanged or reduced.'; end if; v_flag := case when v_pct > v_current then 'none' when v_pct = v_current then 'stalled' else 'regressed' end;
      insert into public.report_lines(batch_id, department, task, project_task_id, percentage, previous_percentage, flag, note, activity, hours_worked, blocker) values (v_batch_id, v_dept, v_task, v_task_row.id, v_pct, v_current, v_flag, v_note, v_activity, v_hours, v_blocker) returning id into v_report_line_id; insert into public.task_activities(project_task_id, employee_id, employee_name, activity_date, description, previous_percent, new_percent, hours_worked, blocker, note, kind, report_line_id, recorded_by) values (v_task_row.id, v_employee.id, v_employee.name, current_date, v_activity, v_current, v_pct, v_hours, v_blocker, v_note, 'report', v_report_line_id, auth.uid()); update public.project_tasks set completion_percent = v_pct, status = case when v_pct = 100 then 'completed' when v_pct > 0 then 'in_progress' else status end, actual_start = case when v_pct > 0 and actual_start is null then current_date else actual_start end, actual_finish = case when v_pct = 100 then current_date else actual_finish end, updated_at = now() where id = v_task_row.id;
    end loop;
  end loop; return v_batch_ids;
end; $$;
grant execute on function public.submit_report(jsonb,date,uuid) to authenticated;

create or replace function public.override_task_completion(p_task_id uuid, p_percent numeric, p_reason text) returns void language plpgsql security definer set search_path = public as $$
declare v_task public.project_tasks%rowtype; v_previous numeric; v_reason text; v_caller public.profiles%rowtype;
begin select * into v_caller from public.profiles where id = auth.uid() and active = true and role = 'manager'; if not found then raise exception 'Manager access required.'; end if; v_reason := nullif(trim(p_reason),''); if v_reason is null then raise exception 'A reason is required to override progress.'; end if; if p_percent is null or p_percent < 0 or p_percent > 100 then raise exception 'Percentage must be a number between 0 and 100.'; end if; select * into v_task from public.project_tasks where id = p_task_id for update; if not found then raise exception 'Task not found.'; end if; v_previous := coalesce(v_task.completion_percent,0); if v_previous = p_percent then raise exception 'The new percentage is the same as the current one.'; end if; insert into public.task_activities(project_task_id, employee_name, activity_date, description, previous_percent, new_percent, kind, recorded_by, reason) values (v_task.id, v_caller.display_name, current_date, 'Manager override: ' || v_reason, v_previous, p_percent, 'override', auth.uid(), v_reason); update public.project_tasks set completion_percent = p_percent, status = case when p_percent = 100 then 'completed' when p_percent > 0 then 'in_progress' else status end, updated_at = now() where id = v_task.id; end; $$;
grant execute on function public.override_task_completion(uuid,numeric,text) to authenticated;

-- Keep report reads scoped to manager, own employee reports, and team-leader scope.
drop policy if exists "reports: read by assigned employee" on public.report_batches; drop policy if exists "reports: read by team leader (own team or own projects)" on public.report_batches; create policy "reports: read by employee own reports" on public.report_batches for select using (is_manager() or employee_id = (select employee_id from public.profiles where id = auth.uid()) or (is_team_leader() and (exists (select 1 from public.profiles p where p.employee_id = report_batches.employee_id and p.team_leader_id = auth.uid()) or exists (select 1 from public.projects pr where pr.id = report_batches.project_id and pr.created_by = auth.uid()))));
drop policy if exists "reports: read by assigned employee" on public.report_lines; drop policy if exists "reports: read by team leader (own team or own projects)" on public.report_lines; create policy "reports: read by employee own reports" on public.report_lines for select using (exists (select 1 from public.report_batches rb where rb.id = report_lines.batch_id and (is_manager() or rb.employee_id = (select employee_id from public.profiles where id = auth.uid()) or (is_team_leader() and (exists (select 1 from public.profiles p where p.employee_id = rb.employee_id and p.team_leader_id = auth.uid()) or exists (select 1 from public.projects pr where pr.id = rb.project_id and pr.created_by = auth.uid()))))));
drop policy if exists "task activities: manager read" on public.task_activities; create policy "task activities: scoped read" on public.task_activities for select using (is_manager() or exists (select 1 from public.project_tasks pt where pt.id = task_activities.project_task_id and (pt.assigned_employee_id = (select employee_id from public.profiles where id = auth.uid()) or (is_team_leader() and exists (select 1 from public.projects pr where pr.id = pt.project_id and pr.created_by = auth.uid())))));
drop policy if exists "task activities: authenticated insert" on public.task_activities; create policy "task activities: no direct insert" on public.task_activities for insert with check (false);
revoke all on function public.submit_report(jsonb,date,uuid) from public; grant execute on function public.submit_report(jsonb,date,uuid) to authenticated; revoke all on function public.override_task_completion(uuid,numeric,text) from public; grant execute on function public.override_task_completion(uuid,numeric,text) to authenticated;
